@ChileFutStats_HostAddress = http://localhost:5121

GET {{ChileFutStats_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ChileFutStats_HostAddress}}/api/equipo/sincronizar
Accept: application/json

###

GET {{ChileFutStats_HostAddress}}/api/equipo
Accept: application/json

###

POST {{ChileFutStats_HostAddress}}/api/equipo/sincronizar?tournamentId=1240&seasonId=89007
Accept: application/json

###

POST {{ChileFutStats_HostAddress}}/api/partido/sincronizar
Accept: application/json

###

POST {{ChileFutStats_HostAddress}}/api/partido/sincronizar?tournamentId=1240&seasonId=89007
Accept: application/json

###

POST {{ChileFutStats_HostAddress}}/api/auth/registro
Content-Type: application/json

{
  "nombreUsuario": "camilo",
  "email": "camilo@example.com",
  "password": "MiClaveSegura123"
}

###

POST {{ChileFutStats_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "nombreUsuario": "camilo",
  "password": "MiClaveSegura123"
}

###